# pylint: disable=unused-argument,used-before-assignment,keyword-arg-before-vararg
from abc import ABC
from collections.abc import Callable, Generator, Hashable, Iterable, Iterator, Mapping
from contextlib import contextmanager
from typing import Any, ClassVar, Literal, Self, overload

from _collections_abc import dict_keys, dict_values


@contextmanager
def no_create(self: Dict) -> Generator: ...

class _Mixin:
	def __init_subclass__(cls, protected_attrs: set[str] | None = None, **kwargs) -> None: ...
	def __reduce__(self) -> tuple[type[Self] | Callable, tuple[dict, bool | None, bool]]: ...
	def __repr__(self, max_length: int | None = -1, max_string: int | None = -1, max_depth: int | None = -1, max_total: int | None = 512, default_convert_value: bool | None = None) -> str: ...

class Dict[K, V](_Mixin, ABC, dict):
	_protected_attrs: ClassVar[set[str]] = {'_protected_attrs'}

	@overload
	def __new__(cls, _map: Mapping | list | None = None, *_: Any, _convert: Literal[True] | None = True, _create: bool | Callable = False, **kwargs) -> BoxDict: ...
	@overload
	def __new__(cls, target: Mapping, *, _convert: Literal[False] = False) -> JDict: ...
	def __new__(cls, _map: Mapping | list | None = None, *_: Any, _convert: bool | None = False, _create: bool | Callable = False, **kwargs) -> BoxDict | JDict: ...

	def _do_convert(self, _val: Any, *args: Any, **kwargs: Any) -> Any: ...
	def __getattr__(self, key: str) -> Any: ...

	def __init_subclass__(cls, protected_attrs: set[str] | None = None, **kwargs) -> None: ...
	@classmethod
	def _warn(cls) -> None: ...

class JDict[K, V](_Mixin, protected_attrs={'_convert', '_wrap', '_t'}):
	def __init__(self, target: Mapping | None = None, *_: Any,  _convert: bool | None = None, _create: bool | Callable = False, **kwargs) -> None: ...
	def __getitem__(self, key: Any) -> Any: ...
	def __getattr__(self, key: str) -> Any: ...
	def __setattr__(self, key: str, value: Any) -> None: ...
	def __delattr__(self, key: Hashable) -> None: ...

	def __len__(self) -> int: ...
	def __setitem__(self, key: Hashable, item: Any) -> None: ...
	def __delitem__(self, key: Hashable) -> None: ...
	def __iter__(self) -> Iterator[Any]: ...
	def __contains__(self, key: Hashable) -> bool: ...
	def get(self, key: Hashable, default: Any = None) -> Any: ...
	def __or__(self, other: Mapping) -> Self | Any: ...
	def __ror__(self, other: Mapping) -> Self | Any: ...
	def __ior__(self, other: Mapping) -> Self: ...
	def __copy__(self) -> Mapping: ...
	def __deepcopy__(self, memo: dict[int, Any] | None = None, _nil: Any = []) -> Mapping: ...
	def copy(self) -> Mapping: ...
	@classmethod
	def fromkeys(cls, iterable: Iterable, value: Any = None) -> Self: ...
	def __reversed__(self) -> Iterator: ...
	def keys(self, _list: bool = True) -> Any: ...
	def items(self, _list: bool = True) -> Any: ...
	def values(self, _list: bool = True) -> list | Any: ...
	def __eq__(self, other: Mapping) -> bool: ...

	def update(self, _map: Mapping | Iterable[tuple[Any, Any]] = (), /, **kwargs: Any) -> None: ...
	def _wrap(self, val: Any) -> Any: ...

class BoxDict[K, V](_Mixin, dict, protected_attrs={'_convert', '_converter', '_create', '_do_convert'}):
	_convert: bool | None = None
	def __init__(self, _map: Mapping | list | None = None, *_: Any, _convert: bool | None = True, _create: bool | Callable = False, _converter: Callable | None = None, **kwargs) -> None:  ...
	def __getattr__(self, key: str) -> Any: ...
	def __setattr__(self, key: str, val: Any) -> None: ...
	def __delattr__(self, key: Hashable) -> None: ...
	def __getitem__(self, key: Any) -> Any: ...
	def __setitem__(self, key: Any, val: Any) -> None: ...
	def _create(self) -> Self: ...  # pyright: ignore[reportRedeclaration]
	_create: Callable | Literal[False]

	def update(self, __m: Any = None, /, **kwargs: Any) -> None: ...

	def keys(self, _list: bool = True) -> list[Hashable] | dict_keys: ...

	@overload
	def values(self) -> list[Any]: ...
	@overload
	def values(self, _list: Literal[True] = True) -> list[Any]: ...
	@overload
	def values(self, _list: Literal[False]) -> Any: ...
	def values(self, _list: bool = True) -> list | dict_values: ...
	def items(self, _list: bool = True) -> list[tuple[Hashable, Any]] | Any: ...
	def hasattr(self, key: str) -> bool: ...
	def getattr(self, key: str, default: Any = None) -> Any: ...

	def __ror__(self: Self, value: Any) -> Self: ...
	def __or__(self: Self, other: Any) -> Self | Any: ...
