from _collections_abc import dict_items, dict_keys, dict_values
# pylint: disable=unused-argument,used-before-assignment,keyword-arg-before-vararg,super-init-not-called
from abc import ABC
from collections.abc import Callable, Generator, Hashable, Iterable, Iterator, Mapping, Sequence
from contextlib import _GeneratorContextManager, contextmanager
from enum import Enum, auto
from typing import Any, ClassVar, Final, Literal, Self, overload

@contextmanager
def no_create(self: Dict) -> Generator: ...

class Dict[K, V](ABC, dict[K, V]):
	_protected_attrs: ClassVar[set[str]] = {'_protected_attrs'}

	@overload
	def __new__(cls: type[Dict[K, V]], target: Mapping[K, V], *, _convert: Literal[False] = False) -> JDict[K, V]: ...
	@overload
	def __new__(cls: type[Dict[K, V]], _map: Mapping[K, V] | Sequence | None = None, *, _convert: Literal[True] | None = True, _create: bool | Callable = False, _converter: Callable | None = None, **kwargs: Any) -> BoxDict[K, V]: ...
	@overload
	def __new__(cls: type[Self], _map: Mapping | Sequence | None = None, *args: Any, _convert: bool | None = False, _create: bool | Callable = False, _converter: Callable | None = None, **kwargs: Any) -> Self: ...
	def __init__(self, _map: Mapping | Sequence | None = None, *_: Any, _convert: bool | None = False, _create: bool | Callable = False, _converter: Callable | None = None, **kwargs) -> None: ...  # pyright: ignore

	def _do_convert(self, _val: Any, *args: Any, **kwargs: Any) -> Any: ...
	def __getattr__(self, key: str) -> Any: ...
	def __setattr__(self, key: str, value: Any) -> None: ...
	def __delattr__(self, key: Hashable) -> None: ...
	def __or__(self, other: Mapping) -> Self | Any: ...
	def __ror__(self, other: Mapping) -> Self | Any: ...
	def __ior__(self, other: Mapping) -> Self: ...

	def __init_subclass__(cls, protected_attrs: set[str] | None = None, **kwargs) -> None: ...  # pyright: ignore
	@classmethod
	def _warn(cls) -> None: ...

	def __reduce__(self) -> tuple[type[Self] | Callable, tuple[dict, bool | None, bool]]: ...
	def __repr__(self, max_length: int | None = -1, max_string: int | None = -1, max_depth: int | None = -1, max_total: int | None = 512, default_convert_value: bool | None = None) -> str: ...

	@overload
	def keys(self, _list: Literal[True] = True) -> list[K]: ...
	@overload
	def keys(self, _list: Literal[False]) -> dict_keys: ...
	@overload
	def values(self, _list: Literal[True] = True) -> list[V]: ...
	@overload
	def values(self, _list: Literal[False]) -> dict_values: ...


class JDict[K, V](Dict[K, V], protected_attrs={'_convert', '_wrap', '_t'}):
	def __init__(self, target: Mapping | None = None, *_: Any,  _convert: bool | None = None, _create: bool | Callable = False, **kwargs) -> None: ...  # pyright: ignore
	def __getitem__(self, key: Any) -> Any: ...
	def __getattr__(self, key: str) -> Any: ...
	def __setattr__(self, key: str, value: Any) -> None: ...
	def __delattr__(self, key: Hashable) -> None: ...

	def __len__(self) -> int: ...
	def __setitem__(self, key: Hashable, item: Any) -> None: ...
	def __delitem__(self, key: Hashable) -> None: ...
	def __iter__(self) -> Iterator[Any]: ...
	def __contains__(self, key: Hashable) -> bool: ...
	def get(self, key: Hashable, default: Any = None) -> Any: ...
	def __or__(self, other: Mapping) -> Self | Any: ...
	def __ror__(self, other: Mapping) -> Self | Any: ...
	def __ior__(self, other: Mapping) -> Self: ...
	def __copy__(self) -> Mapping: ...
	def __deepcopy__(self, memo: dict[int, Any] | None = None, _nil: Any = []) -> Mapping: ...
	def copy(self) -> Mapping: ...
	@classmethod
	def fromkeys(cls, iterable: Iterable, value: Any = None) -> Self: ...
	def __reversed__(self) -> Iterator: ...
	def keys(self, _list: bool = True) -> Any: ...
	def items(self, _list: bool = True) -> Any: ...
	def values(self, _list: bool = True) -> list | Any: ...
	def __eq__(self, other: Mapping) -> bool: ...

	def update(self, _map: Mapping | Iterable[tuple[Any, Any]] = (), /, **kwargs: Any) -> None: ...
	def _wrap(self, val: Any) -> Any: ...

class BoxDict[K, V](Dict[K, V], protected_attrs={'_convert', '_converter', '_create', '_do_convert'}):
	_convert: bool | None = None
	def __init__(self, _map: Mapping | Sequence | None = None, *_: Any, _convert: bool | None = True, _create: bool | Callable = False, _converter: Callable | None = None, **kwargs) -> None:  ...  # pyright: ignore
	def __getattr__(self, key: str) -> Any: ...
	def __setattr__(self, key: str, val: Any) -> None: ...
	def __delattr__(self, key: Hashable) -> None: ...
	def __getitem__(self, key: Any) -> Any: ...
	def __setitem__(self, key: Any, val: Any) -> None: ...
	def _do_convert(self, val: Any, *args: Any, **kwargs: Any) -> Any: ...
	def _create(self) -> Self:  ...
	# _create: Callable | Literal[False]

	def update(self, __m: Any = None, /, **kwargs: Any) -> None: ...

	@overload
	def keys(self, _list: Literal[True] = True) -> list[Hashable]: ...
	@overload
	def keys(self, _list: Literal[False]) -> dict_keys: ...
	@overload
	def values(self, _list: Literal[True] = True) -> list[Any]: ...
	@overload
	def values(self, _list: Literal[False]) -> dict_values: ...
	def items(self, _list: bool = True) -> list[tuple[Hashable, Any]] | Any: ...
	def hasattr(self, key: str) -> bool: ...
	def getattr(self, key: str, default: Any = None) -> Any: ...

	def __ror__(self: Self, value: Any) -> Self: ...
	def __or__(self: Self, other: Any) -> Self | Any: ...


class _Unset(Enum):	UNSET = auto()
_unset: Final = _Unset.UNSET
type Op[O] = O | _Unset
class NewDict[K, V](dict[K, V]):
	_protected_attrs: ClassVar[set[str]]
	_okay_private_keys: set[str] = set()
	_childclass_cache: dict[type, type] = {}
	_cls: None | type = None  # this is used to keep track of if is child class, points to the original not source class
	@classmethod
	def _get_subclass(cls, source: type) -> type: ...
	def __new__(
		cls, source: Mapping[K, V] | Sequence[tuple[K, V]] | None = None, _copy: bool | None = None,
		_convert: Op[bool | None] = _unset, _create: Op[bool] = _unset,
		_converter: Op[Callable] = _unset, _creater: Op[Callable] = _unset,
		**_kwargs: Any,
	) -> Self: ...
	def __init__(
		self, source: Mapping[K, V] | Sequence[tuple[K, V]] | None = None, _copy: bool | None = None,
		_convert: Op[bool | None] = _unset, _create: Op[bool] = _unset,
		_converter: Op[Callable] = _unset, _creater: Op[Callable] = _unset,
		**kwargs: Any,
	) -> None: ...
	def __getattr__(self, key: str) -> Any: ...
	def __setattr__(self, key: str, val: Any) -> None: ...
	def __delattr__(self, key: Hashable) -> None: ...
	def __missing__(self, key: Hashable) -> NewDict: ...
	def __getitem__(self, key: K) -> V: ...
	def __setitem__(self, key: K, val: V) -> None: ...
	def _promote(self, obj: Any) -> Self: ...
	@overload
	def _demote(self, copy: Literal[False] = False, strict: bool = False) -> _GeneratorContextManager: ...
	@overload
	def _demote(self, copy: Literal[True], strict: bool = False) -> Mapping: ...
	def _do_convert(self, val: Any, *args: Any, **kwargs: Any) -> Any: ...
	def _converter(self, val: Any, _: Hashable) -> Self: ...
	def _creater(self, _: Hashable) -> Self: ...
	def __copy__(self) -> Self: ...
	def copy(self) -> Self: ...
	def __ror__(self: Self, other: Any) -> Self | Any: ...
	def __or__(self: Self, other: Any) -> Self | Any: ...
	def update(self, __m: Mapping | Sequence[tuple[K, V]] | None = None, /, **kwargs: Any) -> None: ...
	@overload
	def get(self, key: K) -> V | None: ...
	@overload
	def get(self, key: K, default: V) -> V: ...
	@overload
	def get[T](self, key: K, default: T) -> V | T: ...
	@overload
	def pop(self, key: K) -> V: ...
	@overload
	def pop[T](self, key: K, default: T) -> V | T: ...
	def popitem(self) -> tuple[K, V]: ...
	def setdefault(self, key: K, default: Any = None) -> Any: ...
	def __ior__(self, other: Any) -> Self: ...
	## add support for subclassing and pickling
	def __init_subclass__(cls, protected_attrs: set[str] | None = None, **kwargs: Any) -> None: ...
	def __reduce__(self) -> tuple[Callable, tuple[Mapping, dict[str, SettingValue]]]: ...
	## personal preference, prefer return list instead
	@overload
	def keys(self, _list: Literal[True] = True) -> list[K]: ...
	@overload
	def keys(self, _list: Literal[False]) -> dict_keys[K, V]: ...  # pylint: disable=invalid-sequence-index
	@overload
	def values(self, _list: Literal[True] = True) -> list[V]: ...
	@overload
	def values(self, _list: Literal[False]) -> dict_values[K, V]: ...  # pylint: disable=invalid-sequence-index
	@overload
	def items(self, _list: Literal[True] = True) -> list[tuple[K, V]]: ...
	@overload
	def items(self, _list: Literal[False]) -> dict_items[K, V]: ...  # pylint: disable=invalid-sequence-index
	def hasattr(self, key: str, simple: bool = False) -> bool: ...
	def getattr(self, key: str, default: Any = None, simple: bool = False) -> Any: ...
	def drop(self, *keys: K, copy: bool = False) -> Self: ...

type SettingValue = bool | None | Callable | _Unset
class _Settings[K, V](dict):
	parent: NewDict
	convert: bool | None = None
	create: bool = False
	_keys: frozenset[Literal['_convert', '_create', '_converter', '_creater']] = frozenset(('_convert', '_create', '_converter', '_creater'))
	def __init__(self, parent: NewDict, _convert: Op[bool | None] = _unset, _create: Op[bool] = _unset, _converter: Op[Callable] = _unset, _creater: Op[Callable] = _unset, s: dict = {}) -> None: ...
	def __getattribute__(self, key: str) -> Any: ...
	def __getattr__(self, key: str) -> SettingValue: ...
	def __setattr__(self, key: str, value: SettingValue) -> None: ...
	def __setitem__(self, key: str, value: SettingValue) -> None: ...
	def __contains__(self, key: str | Any) -> bool: ...
	def convert_key(self, key: str) -> str: ...
	def converter(self, val: Any, key: Hashable) -> NewDict[K, V]: ...
	def creater(self, key: Hashable) -> NewDict[K, V]: ...
