target-version = "py313"

[lint]
	# Generic, formatter-friendly config.
	select = ["ALL"]
	# Never enforce `E501` (line length violations). This should be handled by formatters.
	ignore = [
		"ANN003",
		"ANN401",
		"B905",
		"BLE001",
		# "C901",
		"D100",
		"D101",
		"D102",
		"D103",
		"D104",
		"D105",
		"D107",
		"D206",
		# "D209",
		"D300",
		# "D404",
		"DTZ",
		"E401",
		"E402",
		"E501",
		"E701",
		"E702",
		"EM101",
		"EM102",
		"ERA001",
		"EXE002",
		"FBT",
		"G004",  # covered by pylint, (their docs are better for this one)
		"I001",  # covered by isort
		"INP001",
		"N801",
		"N813",
		"PGH003",
		"PGH004",
		"PIE790",
		# "PLR0912",
		"PLR0913",
		"PLR2004",
		"PLW0603",
		"PLW0603",
		"PLW1510",
		"PLW2901",
		"PT009",
		"PT017",
		"PT027",
		"S101",
		"S301",
		"S603",
		"S607",
		"S608",
		"SLF001",
		"T201",
		"TD002",
		"TD003",
		"TD005",
		"TRY002",
		"TRY003",
		"W191",
	]

	# Allow fix for all enabled rules (when `--fix`) is provided.
	fixable = ["ALL"]
	unfixable = ["I001"]

	[lint.pylint]
		max-args = 8

[format]
	indent-style = "tab"
	quote-style = "single"

[flake8-quotes]
	docstring-quotes = "single"
	inline-quotes = "single"
	multiline-quotes = "single"
